version: '3'

services:
  mysqlsrv:
    container_name: mysql-5_7
    image: mysql/mysql-server:8.0
    command: --character-set-server=utf8  --collation-server=utf8_general_ci
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=testedb
    ports:
      - "3307:3306"
    volumes:
      - /home/polonea/devLab/Docker/volumes/mysql:/var/lib/mysql
    networks:
      - mysql-compose-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: adm-mysql
    depends_on:
      - mysqlsrv
    ports:
      - 80:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - mysql-compose-network

networks:
  mysql-compose-network:
    driver: bridge