version: '3'

services:
  server-sb-poc-04:
    container_name: mysql-sb-poc-04
    image: mysql/mysql-server:8.0
    command: --character-set-server=utf8  --collation-server=utf8_general_ci
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=sb-poc-04
    ports:
      - "3309:3306"
#    volumes:
#      - /home/polonea/devLab/Docker/volumes/mysql:/var/lib/mysql
    networks:
      - mysql-cn-sb-poc-04

  phpmyadmin-sb-poc-04:
    image: phpmyadmin/phpmyadmin:latest
    container_name: adm-mysql-sb-poc-04
    depends_on:
      - server-sb-poc-04
    ports:
      - 80:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - mysql-cn-sb-poc-04

networks:
  mysql-cn-sb-poc-04:
    driver: bridge