version: '3'

services:
  server-sb-poc-08:
    container_name: mysql-sb-poc-08
    image: mysql/mysql-server:8.0
    command: --character-set-server=utf8  --collation-server=utf8_general_ci
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=sb-poc-08
    ports:
      - "3313:3306"
    volumes:
      - .docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
#      - /home/polonea/devLab/Docker/volumes/mysql:/var/lib/mysql
    networks:
      - mysql-cn-sb-poc-08
  adminer-sb-poc-08:
    image: adminer
    container_name: adm-mysql-sb-poc-08
    depends_on:
      - server-sb-poc-08
    ports:
      - 8081:8080
    networks:
      - mysql-cn-sb-poc-08
  rabbitmq-sb-poc-08:
    image: rabbitmq:3-management
    hostname: my-rabbit
    #volumes:
    #  - ./rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
    #  - ./rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    #  - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
    #  - ./rabbitmq/logs:/var/log/rabbitmq/log
    ports:
      - 5672:5672
      - 15672:15672
networks:
  mysql-cn-sb-poc-08:
    driver: bridge