spring:
    datasource:
        url: jdbc:mysql://localhost:3311/sb-poc-06?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: root
        tomcat:
            test-while-idle: true
            validation-query: SELECT 1
    jpa:
        hibernate:
            ddl-auto: update
            show_sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                format_sql: true
                type: trace
    batch:
        initialize-schema: always