version: '3'

services:
  server-sb-poc-07:
    container_name: mysql-sb-poc-07
    image: mysql/mysql-server:8.0
    command: --character-set-server=utf8  --collation-server=utf8_general_ci
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=sb-poc-07
    ports:
      - "3312:3306"
    volumes:
      - .docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
#     - /home/polonea/devLab/Docker/volumes/mysql:/var/lib/mysql
    networks:
      - mysql-cn-sb-poc-07
  adminer-sb-poc-07:
    image: adminer
    container_name: adm-mysql-sb-poc-07
    depends_on:
      - server-sb-poc-07
    ports:
      - 8081:8080
    networks:
      - mysql-cn-sb-poc-07
networks:
  mysql-cn-sb-poc-07:
    driver: bridge