version: '3'

services:
  server-sb-poc-11:
    container_name: mysql-sb-poc-11
    image: mysql/mysql-server:8.0
    command: --character-set-server=utf8  --collation-server=utf8_general_ci
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=sb-poc-11
    ports:
      - "3315:3306"
    volumes:
      - .docker2/setup.sql:/docker-entrypoint-initdb.d/setup.sql
#      - .mysql-volume:/var/lib/mysql
    networks:
      - mysql-cn-sb-poc-11
  adminer-sb-poc-11:
    image: adminer
    container_name: adm-mysql-sb-poc-11
    depends_on:
      - server-sb-poc-11
    ports:
      - 8081:8080
    networks:
      - mysql-cn-sb-poc-11
networks:
  mysql-cn-sb-poc-11:
    driver: bridge