version: '3'

services:
  server-sb-poc-09:
    container_name: mysql-sb-poc-09
    image: mysql/mysql-server:8.0
    command: --character-set-server=utf8  --collation-server=utf8_general_ci
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=sb-poc-09
    ports:
      - "3314:3306"
    volumes:
      - .docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
#      - .mysql-volume:/var/lib/mysql
    networks:
      - mysql-cn-sb-poc-09
  adminer-sb-poc-09:
    image: adminer
    container_name: adm-mysql-sb-poc-09
    depends_on:
      - server-sb-poc-09
    ports:
      - 8081:8080
    networks:
      - mysql-cn-sb-poc-09
networks:
  mysql-cn-sb-poc-09:
    driver: bridge